name: Publish to Foundry Package Registry
on:
  workflow_dispatch: 


jobs:
  publish:
    name: Packman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Packer
        id: packs
        uses: aMediocreDad/foundry-db-packer@next
        with:
          inputdir: packs/tinderbox-demo/_source
          packsdir: packs/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packed-packs
          path: packs/