name: Publish to Foundry Package Registry
on:
  release:
    types:
      - published


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get Version Number
        id: tag
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "version=${TAG_NAME//v/}" >> "$GITHUB_OUTPUT"
      - name: Push to Foundry
        id: foundry
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.foundryvtt.com/_api/packages/release_version/'
          customHeaders: '{ "Content-Type": "application/json", "Authorization": "${{ secrets.FOUNDRY_API_KEY }}" }'
          data:
            '{
              "id": "litm",
              "release": {
                "version": "${{ steps.tag.outputs.version }}",
                "manifest": "https://raw.githubusercontent.com/aMediocreDad/litm/${{ github.event.release.tag_name }}/system.json",
                "notes": "https://github.com/aMediocreDad/litm/releases/tag/${{ github.event.release.tag_name }}",
                "compatibility": {
                  "minimum": "12",
                  "verified": "12",
                  "maximum": "12"
                }
              }
            }'
      - name: Summary
        run: |
          echo "**Version:** ${{ steps.tag.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Release Notes:** ${{ github.event.release.html_url }}" >> $GITHUB_STEP_SUMMARY
          echo "**Published:** ${{ steps.foundry.outputs.response.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**URL:** ${{ steps.foundry.outputs.response.page }}" >> $GITHUB_STEP_SUMMARY