name: Publish to Foundry Package Registry
on:
  release:
    types:
      - published


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish FoundryVTT Package
        uses: illandril/FoundryVTT-package-release-action@v1
        with:
            package-release-token: ${{ secrets.FOUNDRY_API_KEY }}
            manifest-url:  https://raw.githubusercontent.com/aMediocreDad/litm/${{ github.event.release.tag_name }}/system.json